version: '3.9'

services:
  db:
    container_name: hackernews-clone-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ~/prisma-postgres:/var/lib/postgresql/data
  server:
    container_name: hackernews-clone-graphql
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_PATH}