version: '3.9'

services:
  db:
    container_name: hackernews-clone-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ~/prisma-postgres:/var/lib/postgresql/data
  server:
    container_name: hackernews-clone-graphql
    restart: unless-stopped
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_PATH}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./schema.graphql:/app/schema.graphql
  ui:
    container_name: hackernews-clone-ui
    build: 
      context: ./ui
    volumes:
      - ./ui:/app
      - ./ui/node_modules:/app/node_modules
    ports:
      - '3000:3000'
    restart: unless-stopped
