// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/DefaultLayout.vue')['default']
    MdiMenuUp: typeof import('~icons/mdi/menu-up')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
  }
}

export { }
