version: '3.8'

services:
  ui:
    container_name: hackernews-clone-ui
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - '4000:4000'
    restart: unless-stopped